[package]
name = "despero"
version = "0.0.1"
edition = "2021"

[dependencies]
colored = "2.0.0"
as-slice = "0.2.1"

ash = "0.37.0"
nalgebra = "0.31.2"
vk-shader-macros = "0.2.8"
gpu-allocator = "0.20.0"

winit = "0.27.4"
ash-window = "0.12.0"
raw-window-handle = "0.5.0"

[features]
x11 = []
windows = []

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
