[package]
name = "despero"
version = "0.0.1"
edition = "2021"

[dependencies]
ash = "0.37.0"
winit = "0.27.4"
ash-window = "0.12.0"
raw-window-handle = "0.5.0"

[features]
default = ["x11"]
x11 = []
windows = []

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
